arr = input().split()
a,b = int(arr[0]), int(arr[1])
print(1) if a>=b else print(0)
print(1) if a>b else print(0)
print(1) if a<=b else print(0)
print(1) if a<b else print(0)
print(1) if a==b else print(0)
print(1) if a!=b else print(0)